### ISSUE TITLE
use svgs

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ft-icons#61]
next is now using o-icons svgs + image service https://github.com/Financial-Times/next-sass-setup/blob/master/main.scss#L16

I was originally intending to branch o-icons and create a PR but working on the svg implementation has highlighted a few things that would need to be resolved first.

- non-silent mode isn't really possible in the same way as icon colour can't be overridden except for in the sass
- I think image service and paths to svg assets on buildservice need baking into the module, but other people may disagree

**Comment by kaelig** [comment]
@wheresrhys Since we can't think of a way to make svg icons work cross browsers with `@extend` or mixins, while being "colourable", I'm not sure we can make the version of o-ft-icons available through the build service fully use SVG.

Maybe we could have two ways of doing this:
1. build service: uses the icon font
2. Sass: helpers for SVGs *and* the icon font

Thoughts?

**Comment by wheresrhys** [comment]
yep, looks like a good compromise

**Comment by triblondon** [comment]
Succeeded by #90
